# Generated by Django 4.1.4 on 2022-12-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablica_ogloszen', '0002_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tablica_ogloszen.categories'),
        ),
        migrations.AddField(
            model_name='comments',
            name='announcement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tablica_ogloszen.announcement'),
        ),
    ]
