# Generated by Django 4.1.4 on 2022-12-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablica_ogloszen', '0003_announcement_categories_comments_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
